export const mockProducts = [
  {
    id: "p1",
    categoryId: "c1",
    name: "Minimal Wooden Chair",
    slug: "minimal-wooden-chair",
    description: "A simple and elegant wooden chair made from oak wood.",
    price: 120.5,
    rating: 4.5,
    bestseller: true,
    weight: 8,
    sku: "CHAIR-001",
    stock: 25,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "c1",
      name: "Furniture",
    },
    images: [
      {
        id: "img1",
        productId: "p1",
        imageUrl: "https://placehold.co/600x400",
        altText: "Wooden chair",
        sortOrder: 1,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "img2",
        productId: "p2",
        imageUrl: "https://placehold.co/600x400/EEE/31343C?font=lato&text=Lato",
        altText: "Metal chair",
        sortOrder: 2,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "img3",
        productId: "p3",
        imageUrl: "https://placehold.co/600x400/EEE/31343C?font=raleway&text=Raleway",
        altText: "Stone chair",
        sortOrder: 3,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    variants: [
      {
        id: "v1",
        productId: "p1",
        name: "Color",
        value: "Brown",
        priceAdjustment: 0,
        stock: 10,
        sku: "CHAIR-001-BRN",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "v2",
        productId: "p2",
        name: "Color",
        value: "Gray",
        priceAdjustment: 0,
        stock: 10,
        sku: "CHAIR-002-BRN",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
        {
        id: "v3",
        productId: "p3",
        name: "Color",
        value: "Purple",
        priceAdjustment: 0,
        stock: 10,
        sku: "CHAIR-003-BRN",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  {
    id: "p2",
    categoryId: "c2",
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    description: "Noise-cancelling over-ear wireless headphones.",
    price: 89.99,
    rating: 4.5,
    bestseller: true,
    weight: 1,
    sku: "HEAD-002",
    stock: 50,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "c2",
      name: "Electronics",
    },
    images: [
      {
        id: "img2",
        productId: "p2",
        imageUrl: "https://placehold.co/600x400",
        altText: "Headphones",
        sortOrder: 1,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    variants: [
      {
        id: "v2",
        productId: "p2",
        name: "Color",
        value: "Black",
        priceAdjustment: 0,
        stock: 30,
        sku: "HEAD-002-BLK",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  {
    id: "p3",
    categoryId: "c1",
    name: "Modern Coffee Table",
    slug: "modern-coffee-table",
    description: "Stylish coffee table with tempered glass top.",
    price: 210,
    rating: 4.5,
    bestseller: true,
    weight: 15,
    sku: "TABLE-003",
    stock: 12,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "c1",
      name: "Furniture",
    },
    images: [
      {
        id: "img3",
        productId: "p3",
        imageUrl: "https://placehold.co/600x400",
        altText: "Coffee table",
        sortOrder: 1,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    variants: [],
  },

  {
    id: "p4",
    categoryId: "c3",
    name: "Running Shoes",
    slug: "running-shoes",
    description: "Lightweight running shoes for daily training.",
    price: 75,
    rating: 4.5,
    bestseller: true,
    weight: 1,
    sku: "SHOE-004",
    stock: 40,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "c3",
      name: "Sports",
    },
    images: [
      {
        id: "img4",
        productId: "p4",
        imageUrl: "https://placehold.co/600x400",
        altText: "Running shoes",
        sortOrder: 1,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    variants: [
      {
        id: "v4",
        productId: "p4",
        name: "Size",
        value: "42",
        priceAdjustment: 0,
        stock: 20,
        sku: "SHOE-004-42",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  {
    id: "p5",
    categoryId: "c4",
    name: "Smart Watch",
    slug: "smart-watch",
    description: "Fitness tracking smart watch with heart rate monitor.",
    price: 199.99,
    rating: 4.5,
    bestseller: true,
    weight: 0.5,
    sku: "WATCH-005",
    stock: 18,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "c4",
      name: "Wearables",
    },
    images: [
      {
        id: "img5",
        productId: "p5",
        imageUrl: "https://placehold.co/600x400",
        altText: "Smart watch",
        sortOrder: 1,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    variants: [
      {
        id: "v5",
        productId: "p5",
        name: "Color",
        value: "Silver",
        priceAdjustment: 10,
        stock: 8,
        sku: "WATCH-005-SLV",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];