export const mockBestSellingProducts = [
  {
    id: "p6",
    categoryId: "c5",
    name: "Ergonomic Gaming Desk",
    slug: "ergonomic-gaming-desk",
    description:
      "A spacious ergonomic gaming desk with RGB lighting, cable management system, and adjustable height for long gaming or work sessions.",
    ingredients:
      "Carbon fiber composite, aluminum frame, tempered glass accents",
    price: 349.99,
    rating: 4.8,
    bestseller: true,
    weight: 28,
    sku: "DESK-006",
    stock: 15,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "c5",
      name: "Gaming Furniture",
    },
    images: [
      {
        id: "img6",
        productId: "p6",
        imageUrl: "https://placehold.co/600x400/111/EEE?text=Gaming+Desk",
        altText: "Gaming desk setup",
        sortOrder: 1,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "img7",
        productId: "p6",
        imageUrl: "https://placehold.co/600x400/222/EEE?text=RGB+Lighting",
        altText: "Desk RGB lighting",
        sortOrder: 2,
        isFeatured: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    variants: [
      {
        id: "v6",
        productId: "p6",
        name: "Color",
        value: "Black",
        priceAdjustment: 0,
        stock: 10,
        sku: "DESK-006-BLK",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "v7",
        productId: "p6",
        name: "Size",
        value: "160cm",
        priceAdjustment: 20,
        stock: 5,
        sku: "DESK-006-160",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "p7",
    categoryId: "c6",
    name: "Smart Air Purifier Pro",
    slug: "smart-air-purifier-pro",
    description:
      "A high-performance smart air purifier with HEPA13 filtration, real-time air quality monitoring, and app control for cleaner indoor air.",
    ingredients:
      "ABS plastic, HEPA13 filter, activated carbon layer, silicone seals",
    price: 259.0,
    rating: 4.7,
    bestseller: true,
    weight: 6.2,
    sku: "AIR-007",
    stock: 22,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      id: "c6",
      name: "Home Appliances",
    },
    images: [
      {
        id: "img8",
        productId: "p7",
        imageUrl: "https://placehold.co/600x400/0A0A0A/FFFFFF?text=Air+Purifier",
        altText: "Smart air purifier front view",
        sortOrder: 1,
        isFeatured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "img9",
        productId: "p7",
        imageUrl:
          "https://placehold.co/600x400/1A1A1A/FFFFFF?text=Air+Quality+Display",
        altText: "Air quality display screen",
        sortOrder: 2,
        isFeatured: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    variants: [
      {
        id: "v8",
        productId: "p7",
        name: "Color",
        value: "White",
        priceAdjustment: 0,
        stock: 12,
        sku: "AIR-007-WHT",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "v9",
        productId: "p7",
        name: "Coverage Area",
        value: "Up to 60sqm",
        priceAdjustment: 30,
        stock: 10,
        sku: "AIR-007-60",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];